language: node_js
install: npm install
script: npm run build
deploy:
  provider: heroku
  api_key:
    secure: sbT08vql4Ms9680MeiKBYKaPEIAb1ozdX7pHrjK6hUp8fzhaCrnZj38uuk9N74ruAfhCy+hVd149EC5BpKHQTxxQ/sP3sP9m+u6g8sGX/vBrRWGemPkyZd3YBA+G9PVEiCHuw0XVE0hbJfXxoedFmJFpPcqp6Wog4RZaLWw3ixnJxTHkbWP/eQfCeIaWcbrQEkdcyZzHrvKOTenzfyUCH94sInZkdW4fW68Z3wi4C3jSntfl7GMCxU5tf9IOGZZM2cdE090nzHQq46EKw9NcBIQid+Q2n3AP2y5KG9V7pTYu3pfNwTnS5RhUgZlNawQ9l2sSUBwmLx8NnI4zf6JYNWdNJLbu2TS7M0QIha8YNitbQWAMB3yLoTdhFEUCAS00hdRgPt86jz8vafH2E5KC8QqMDAaf7Ido1LcQ4Ra03ny2/MlWwHLphY5BFZEA+4BY3kX3lKMcotT6jdNEwuVYUxJ9zIlxKD3mowHtOX9sK/T5KqmLdSiZyBCIIMx807Zk9XHjwt2MZYRdYKv2ocxyPe599eARKImcKJjf6w3Y8ETxSFQDLRm9I44V8JL86p+gotbSZUq/bKh14vr22Vlu1fezgABFk2lpobfaVEQ5XgLmfEfXGHtAC9ZFdfumT+Sf4y6zlopDt3Ks625wVjcy5dwWXY0NGR3h3JTEWtgv1cI=
